version: "2"
services:
  mongo:
      image: mongo:3.4
      container_name: mongo.local
      hostname: mongo.local
      ports:
        - "27017:27017"

  redis:
      image: redis
      ports:
        - "6379:6379"

  keystone:
      image: tuxmonteiro/keystone
      container_name: k1.local
      hostname: k1.local
      ports:
        - "5000:5000"
        - "35357:35357"

  statsd:
      image: tuxmonteiro/statsite
      ports:
        - "8125:8125/udp"
      environment:
        - STREAM_CMD=/usr/bin/nodejs /bin/sinks/opentsdb.js opentsdb.local 4242 _t_
        - STATSITE_FLUSH_INTERVAL=1
        - USE_TYPE_PREFIX=0
      volumes:
        - /tmp:/tmp
      links:
        - opentsdb:opentsdb.local

  opentsdb:
      image: tuxmonteiro/opentsdb
      container_name: opentsdb.local
      hostname: opentsdb.local
      ports:
        - "4242:4242"
        - "60000:60000"
        - "60010:60010"
        - "60030:60030"
        - "16010:16010"

  grafana:
      image: grafana/grafana
      environment:
          - GF_SECURITY_ADMIN_PASSWORD=admin
      ports:
          - 3000:3000
      links:
          - opentsdb:opentsdb.local

