version: "2"
services:
  mongo:
      image: mongo:3.4
      ports:
        - "27017:27017"

  keystone:
      image: tuxmonteiro/keystone
      container_name: k1.local
      hostname: k1.local
      ports:
        - "5000:5000"
        - "35357:35357"

#  horizon:
#      image: pataquets/openstack-dashboard
#      container_name: horizon.local
#      hostname: horizon.local
#      ports:
#        - "8800:80"
#      environment:
#        - OPENSTACK_HOST=k1.local
#        - OPENSTACK_KEYSTONE_URL=http://k1.local:5000/v3
#      links:
#        - keystone:k1.local

  broker:
      image: vromero/activemq-artemis:1.5.4
      ports:
        - "61616:61616"
        - "8161:8161"
        - "5672:5672"
      environment:
        - ARTEMIS_USERNAME=guest
        - ARTEMIS_PASSWORD=guest
        - ARTEMIS_MIN_MEMORY=512M
        - ARTEMIS_MAX_MEMORY=1024M
        - ARTEMIS_PERF_JOURNAL=AUTO

  statsd:
      image: tuxmonteiro/statsite
      ports:
        - "8125:8125/udp"
      depends_on:
        - graphite
      environment:
        - STREAM_CMD=python /bin/sinks/graphite.py grafite.local 2003 statsite
        - STATSITE_FLUSH_INTERVAL=1
        - USE_TYPE_PREFIX=0
      links:
        - graphite:graphite.local


  graphite:
      #image: ennexa/graphite
      image: tuxmonteiro/graphite-stack
      container_name: graphite.local
      hostname: graphite.local
      ports:
        - "2003:2003"
        - "443:443"

  grafana:
      image: grafana/grafana
      ports:
        - "3000:3000"
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=admin
      depends_on:
        - statsd

  grou:
      build: .
      environment:
        - MONGO_HOST=mongo.local
        - KEYSTONE_URL=http://k1.local:5000/v3
        - KEYSTONE_DOMAIN_CONTEXT=grou
        - BROKER_CONN=tcp://broker.local:61616?blockOnDurableSend=false&consumerWindowSize=0&protocols=Core
      ports:
        - "8080:8080"
      links:
        - mongo:mongo.local
        - keystone:k1.local
        - broker:broker.local
