version: "3"
services:
  mongo:
      image: mongo:3.4
      container_name: mongo.local
      hostname: mongo.local
      ports:
        - "27017:27017"

  redis:
      image: redis
      ports:
        - "6379:6379"

  keystone:
      image: tuxmonteiro/keystone
      container_name: k1.local
      hostname: k1.local
      ports:
        - "5000:5000"
        - "35357:35357"

  statsd:
      image: tuxmonteiro/statsite
      ports:
        - "8125:8125/udp"
      environment:
        - STREAM_CMD=tee -a /tmp/out
        - STATSITE_FLUSH_INTERVAL=1
        - USE_TYPE_PREFIX=0
      volumes:
        - /tmp:/tmp

  grou:
      build: .
      environment:
        - MONGO_HOST=mongo.local
        - KEYSTONE_URL=http://k1.local:5000/v3
        - KEYSTONE_DOMAIN_CONTEXT=grou
        - BROKER_CONN=tcp://broker.local:61616?blockOnDurableSend=false&consumerWindowSize=0&protocols=Core
      ports:
        - "8080:8080"
      links:
        - mongo:mongo.local
        - keystone:k1.local
        - redis:redis